server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: CoreDomain
          uri: http://localhost:8081
          predicates:
            - Path=/classes/**, 
        - id: SupportingDomain
          uri: http://localhost:8082
          predicates:
            - Path=/students/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: CoreDomain
          uri: http://coreDomain:8080
          predicates:
            - Path=/classes/**, 
        - id: SupportingDomain
          uri: http://supportingDomain:8080
          predicates:
            - Path=/students/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
