---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CoreDomain
  labels:
    app: CoreDomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CoreDomain
  template:
    metadata:
      labels:
        app: CoreDomain
    spec:
      containers:
        - name: CoreDomain
          image: username/CoreDomain:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SupportingDomain
  labels:
    app: SupportingDomain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SupportingDomain
  template:
    metadata:
      labels:
        app: SupportingDomain
    spec:
      containers:
        - name: SupportingDomain
          image: username/SupportingDomain:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: CoreDomain
  labels:
    app: CoreDomain
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CoreDomain


---


apiVersion: v1
kind: Service
metadata:
  name: SupportingDomain
  labels:
    app: SupportingDomain
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SupportingDomain

